# Generated by Django 5.2.13 on 2026-05-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('electronics', 'Điện tử'), ('fashion', 'Thời trang'), ('home_living', 'Nhà cửa & Đời sống'), ('beauty', 'Làm đẹp'), ('food', 'Thực phẩm')], default='electronics', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('e_wallet', 'Ví điện tử')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Hoàn thành'), ('pending', 'Đang xử lý'), ('cancelled', 'Đã hủy')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
        ),
    ]
