# Generated by Django 5.2.13 on 2026-05-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order_count', models.IntegerField(default=0)),
                ('avg_order_value', models.FloatField(default=0)),
                ('last_active_days', models.IntegerField(default=0)),
                ('is_fraudulent', models.BooleanField(default=False)),
                ('preferred_category', models.CharField(blank=True, max_length=50, null=True)),
                ('email_open_rate', models.FloatField(default=0)),
                ('satisfaction_score', models.FloatField(default=0)),
                ('loyalty_score', models.IntegerField(default=0)),
                ('loyalty_level', models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('platinum', 'Bạch kim')], default='bronze', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động')], default='active', max_length=20)),
                ('segment', models.CharField(blank=True, max_length=50, null=True)),
                ('churn_risk', models.CharField(blank=True, max_length=50, null=True)),
                ('churn_probability', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Tích cực'), ('neutral', 'Trung lập'), ('negative', 'Tiêu cực')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='customers.customer')),
            ],
        ),
    ]
